server:
  port: 8762


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
spring:
  cloud:
    refresh:
      enabled: false
  application:
    name: eureka-server

logging:
  level:
    org.springframework.boot: debug