server:
  port: 8761


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
spring:
  cloud:
    refresh:
      enabled: true
  application:
    name: eureka-server
