spring:
  cloud:
    loadbalancer:
      stats:
        micrometer:
          enabled: true
  application:
    name: card-service
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:9888
logging:
  level:
    org.springframework: debug
server:
  port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - env
          - metrics
          - prometheus